services:
  db:
    container_name: postgres
    image: postgres:14.9
    environment:
      POSTGRES_USER: nguyenhv
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  fullstack-professional-api:
    container_name: fullstack-professional-api
    image: nguyenhv236/fullstack-professional-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge

volumes:
  db: